# Generated by Django 4.1.7 on 2023-03-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='PhoneNo',
            new_name='phone',
        ),
    ]
