# Generated by Django 4.1.7 on 2023-03-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_phoneno_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
